name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      - name: "Install uv"
        uses: astral-sh/setup-uv@v4

      - name: "Set up Python"
        run: uv python install 3.12

      - name: "Install requirements"
        run: scripts/setup

      - name: "Lint"
        run: scripts/lint
